name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Tjek kode ud
        uses: actions/checkout@v3

      - name: Opsæt JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Byg med Maven
        run: mvn clean package

      - name: Kør tests
        run: mvn test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Log ind på Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy til Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          package: target/*.jar
